### ISSUE TITLE
Create a small plugin to style frontend when the plugins do not have any frontend

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/gae-plugin-framework#48]
So i should be able to use interactive explorer without an auth plugin

![screen shot 2018-03-30 at 11 54 17](https://user-images.githubusercontent.com/1122760/38133824-1cf631be-3411-11e8-9e41-7d4851420bce.png)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/gae-plugin-framework#5
